/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwcd_sy_clib_LibTest */

#ifndef _Included_com_gwcd_sy_clib_LibTest
#define _Included_com_gwcd_sy_clib_LibTest
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_gwcd_sy_clib_LibTest
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gwcd_sy_clib_LibTest_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_gwcd_sy_clib_LibTest
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gwcd_sy_clib_LibTest_nativeRelease
    (JNIEnv *, jclass);

/*
 * Class:     com_gwcd_sy_clib_LibTest
 * Method:    LongTimeTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gwcd_sy_clib_LibTest_LongTimeTask
  (JNIEnv *, jclass);

/*
 * Class:     com_gwcd_sy_clib_LibTest
 * Method:    LongTimeTask2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gwcd_sy_clib_LibTest_LongTimeTask2
    (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
